help:
  app_name: f1_trainer
  header: == ${hydra.help.app_name} ==
  template: |-
    ${hydra.help.header}

    A trainer for a NWM-CNN (F1 Model) to predict flood extents

    ${hydra.help.footer}
  footer: |-
    Powered by Hydra (https://hydra.cc)
    Use --hydra-help to view Hydra specific help
job:
  name: ${name}
  chdir: True
run:
  dir: ${hydra:runtime.cwd}/runs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
sweep:
  dir: multirun
  subdir: ${hydra.job.override_dirname}
